### ISSUE TITLE
Box color transparency doesn't work

### ISSUE THREAD

**Issue by khalidahmedshalabi** [Gammix/fader.inc#3]

**Comment by Gammix** [comment]
Do you use TextDrawUseBox with valid box size? 
Because box fade only works if you have a real TD box.

**Comment by khalidahmedshalabi** [comment]
A real TD box? Yeah, it's just normal. If I have a black box with transparency (0x00000055), after fading it turns into solid black (0x000000FF).

**Comment by Gammix** [comment]
Should be fixed by now. 

Thanks for reporting.
